## 异常

**异常** ：指的是程序在执行过程中，出现的非正常的情况，最终会导致JVM的非正常停止。

在Java等面向对象的编程语言中，异常本身是一个类，产生异常就是创建异常对象并抛出了一个异常对象。Java处理异常的方式是中断处理。

**异常指的并不是语法错误,语法错了,编译不通过,不会产生字节码文件,根本**不能运行

**异常体系**

异常机制其实是帮助我们找到程序中的问题，异常的根类是 java.lang.**Throwable** ，其下有两个子类：**java.lang.Error** 与 java.lang.**Exception** ，平常所说的异常指 java.lang.**Exception** 。

![image-20200925212008120](C:\Users\一个人的旅程\AppData\Roaming\Typora\typora-user-images\image-20200925212008120.png)

**Throwable体系：**

+ Error:严重错误Error，无法通过处理的错误，只能事先避免，好比绝症。
+ Exception:表示异常，异常产生后程序员可以通过代码的方式纠正，使程序继续运行，是必须要处理的。好比感冒、阑尾炎。

**Throwable中的常用方法**：

+ public void **printStackTrace()** :打印异常的详细信息。
  包含了异常的类型,异常的原因,还包括异常出现的位置,在开发和调试阶段,都得使用printStackTrace。
+ public String **getMessage()** :获取发生异常的原因。
  提示给用户的时候,就提示错误原因。
+ public String **toString()** :获取异常的类型和异常描述信息(不用)。

![image-20200925212333647](C:\Users\一个人的旅程\AppData\Roaming\Typora\typora-user-images\image-20200925212333647.png)

其中，Demo.java:7,表示第7行出错

### 异常分类

**异常(Exception)的分类**:根据在编译时期还是运行时期去检查异常?

+ **编译时期异常**:checked异常。在编译时期,就会检查,如果没有处理异常,则编译失败。(如日期格式化异常)
+ **运行时期异常**:runtime异常。在运行时期,检查异常.在编译时期,运行异常不会编译器检测(不报错)。(如数学异常

![image-20200925212516702](C:\Users\一个人的旅程\AppData\Roaming\Typora\typora-user-images\image-20200925212516702.png)

**异常的产生过程解析**

![image-20200925212610568](C:\Users\一个人的旅程\AppData\Roaming\Typora\typora-user-images\image-20200925212610568.png)

产生异常-------》jvm将异常信息封装到对象当中------》抛给调用者，main（）--------》

## 异常处理

Java异常处理的五个关键字：try、catch、finally、throw、throws

**抛出异常**

在编写程序时，我们必须要考虑程序出现问题的情况。比如，在定义方法时，方法需要接受参数。那么，当调用方
法使用接受到的参数时，首先需要先对参数数据进行合法的判断，数据若不合法，就应该告诉调用者，传递合法的
数据进来。这时需要使用抛出异常的方式来告诉调用者。

在java中，提供了一个throw关键字，它用来抛出一个指定的异常对象。那么，抛出一个异常具体如何操作呢？
1. 创建一个异常对象。封装一些提示信息(信息可以自己编写)。
2. 需要将这个异常对象告知给调用者。怎么告知呢？怎么将这个异常对象传递到调用者处呢？通过关键字throw
就可以完成。throw 异常对象。
throw用在方法内，用来抛出一个异常对象，将这个异常对象传递到调用者处，并结束当前方法的执行。

**使用格式：**

throw new 异常类名(参数);

+ throw new NullPointerException("要访问的arr数组不存在");
+ throw new ArrayIndexOutOfBoundsException("该索引在数组中不存在，已超出范围");

在使用的时候：

```
if(index<0 || index>arr.length‐1){
             /*
             判断条件如果满足，当执行完throw抛出异常对象后，方法已经无法继续运算。这时就会结束当前方法的执行，并将异常告知给调用者。这时就需要通过异常来解决。
              */
             throw new ArrayIndexOutOfBoundsException("哥们，角标越界了~~~");
        }
```

注意：如果产生了问题，我们就会throw将问题描述类即异常进行抛出，也就是将问题返回给该方法的调用者。
那么对于调用者来说，该怎么处理呢？一种是进行捕获处理，另一种就是继续讲问题声明出去，使用throws声明处理。

 **Objects非空判断**

类Objects的一些静态方法是null-save（空指针安全的）或null-tolerant（容忍空指针的），那么在它的源码中，对对象为null的值进行了抛出异常操作。
public static <T> T requireNonNull(T obj) :查看指定引用对象不是null。
查看源码发现这里对为null的进行了抛出异常操作：

```
public static <T> T requireNonNull(T obj) {
    if (obj == null)
       throw new NullPointerException();  
    return obj;
}
```

**声明异常throws：**

**声明异常**：将问题标识出来，报告给调用者。如果方法内通过throw抛出了编译时异常，而没有捕获处理（稍后讲解该方式），那么必须通过throws进行声明，让调用者去处理。
关键字throws运用于方法声明之上,用于表示当前方法不处理异常,而是提醒该方法的调用者来处理异常(抛出异常).

**声明格式：**

```java
修饰符 返回值类型 方法名(参数) throws 异常类名1,异常类名2…{   } 
public class ThrowsDemo {
    public static void main(String[] args) throws FileNotFoundExce
```

例子：

```java
public class ThrowsDemo {
    public static void main(String[] args) throws FileNotFoundException {
        read("a.txt");
    }
    // 如果定义功能时有问题发生需要报告给调用者。可以通过在方法上使用throws关键字进行声明
    public static void read(String path) throws FileNotFoundException {
        if (!path.equals("a.txt")) {//如果不是 a.txt这个文件
            // 我假设  如果不是 a.txt 认为 该文件不存在 是一个错误 也就是异常  throw
            throw new FileNotFoundException("文件不存在");
        }
    }
}
```

这是其中一个异常处理，在方法上多加：throws exception，方法体内部throws new exception。mian函数调用了read函数，所以main函数也要加上声明

throws用于进行异常类的声明，若该方法可能有多种异常情况产生，那么在throws后面可以写多个异常类，用逗
号隔开。

**捕获异常：try....catch**

如果异常出现的话,会立刻终止程序,所以我们得处理异常:**有两种方式**
1. 该方法不处理,而是声明抛出,由该方法的调用者来处理(throws)。
2. 在方法中使用try-catch的语句块来处理异常。   

try-catch的方式就是捕获异常。 

**例子**：

```java
public class TryCatchDemo {
    public static void main(String[] args) {
        try {// 当产生异常时，必须有处理方式。要么捕获，要么声明。
            read("b.txt");
        } catch (FileNotFoundException e) {// 括号中需要定义什么呢？
           //try中抛出的是什么异常，在括号中就定义什么异常类型  
            System.out.println(e);
        }
        System.out.println("over");
    }
    /*
     *
     * 我们 当前的这个方法中 有异常  有编译期异常
     */
    public static void read(String path) throws FileNotFoundException {
        if (!path.equals("a.txt")) {//如果不是 a.txt这个文件
            // 我假设  如果不是 a.txt 认为 该文件不存在 是一个错误 也就是异常  throw
            throw new FileNotFoundException("文件不存在");
        }
    }
}
```

使用read函数的时候可能会产生异常。try里面的 是可能会出现异常的代码，catch里面是对捕获异常的处理。

**获取异常的信息**

Throwable类中定义了一些查看方法:

+ public String getMessage() :获取异常的描述信息,原因(提示给用户的时候,就提示错误原因。
+ public String toString() :获取异常的类型和异常描述信息(不用)。
+ public void printStackTrace() :打印异常的跟踪栈信息并输出到控制台

包含了异常的类型,异常的原因,还包括异常出现的位置,在开发和调试阶段,都得使用printStackTrace。

**finally代码块**

有一些特定的代码无论异常是否发生，都需要执行。另外，因为异常会引发程序跳转，导致有些语句执行不到。而finally就是解决这个问题的，在finally代码块中存放的代码都是一定会被执行的。

**什么时候的代码必须最终执行？**
当我们在try语句块中打开了一些物理资源(磁盘文件/网络连接/数据库连接等),我们都得在使用完之后,最终关闭打开
的资源。

finally的语法:
try...catch....finally:自身需要处理异常,最终还得关闭资源。
**注意:finally不能单独使用。**

当只有在try或者catch中调用退出JVM的相关方法,此时finally才不会执行,否则finally永远会执行。

**异常的注意事项**

1. 多个异常的处理
   + 多个异常分别处理。
   + 多个异常一次捕获，多次处理。
   + 多个异常一次捕获一次处理。

一般我们是使用一次捕获多次处理方式，格式如下：

```java
try{
     编写可能会出现异常的代码
}catch(异常类型A  e){  当try中出现A类型异常,就用该catch来捕获.
     处理异常的代码
     //记录日志/打印异常信息/继续抛出异常
}catch(异常类型B  e){  当try中出现B类型异常,就用该catch来捕获.
     处理异常的代码
     //记录日志/打印异常信息/继续抛出异常
}
```

注意:这种异常处理方式，要求多个catch中的异常不能相同，并且若catch中的多个异常之间有子父类异常的关系，那么子类异常要求在上面的catch处理，父类异常在下面的catch处理。

2. 运行时异常被抛出可以不处理。即不捕获也不声明抛出。
3. 如果finally有return语句,永远返回finally中的结果,避免该情况

4. 如果父类抛出了多个异常,子类重写父类方法时,抛出和父类相同的异常或者是父类异常的子类或者不抛出异常。
5. 父类方法没有抛出异常，子类重写父类该方法时也不可抛出异常。此时子类产生该异常，只能捕获处理，不能声明抛出

## 自定义异常

**为什么需要自定义异常类:**

有时候，我们根据自己业务的异常情况来定义异常类。

**异常类如何定义:**

1. 自定义一个编译期异常: 自定义类 并继承于 java.lang.Exception 。

2. 自定义一个运行时期的异常类:自定义类 并继承于 java.lang.RuntimeException 。

**例子：**

```java
public class RegisterException extends Exception {
    /**
     * 空参构造
     */
    public RegisterException() {
    }
    /**
     * @param message 表示异常提示，有参构造
     */
    public RegisterException(String message) {
        super(message);
    }
}
```

